### ISSUE TITLE
npm twitter-validate package is empty

### ISSUE THREAD

**Issue by ghost** [benderham/twitter-validate#1]
Updating twitter-validate to 1.0.6, "Can not resolve module 'twitter - validate" error occurred.
similar errors also occurred in Runkit.
https://runkit.com/npm/twitter-validate

There are only package.json and README.md in the installed package.
As in 1.0.4 and earlier, I would like to add lib to the repository.

**Comment by benderham** [comment]
`lib` folder is now included in the npm package, as per 1.0.4 and earlier.
